Drivers Table

In [1]:
import pandas as pd

drivers_df = pd.read_csv('/content/drivers.csv')
print("Null values in each column of the drivers table:")
print(drivers_df.isnull().sum())

Null values in each column of the drivers table:
driver_id           0
base_zone           0
employment_type     0
years_experience    0
training_score      7
driver_rating       0
shift_preference    0
active_flag         0
dtype: int64

In [2]:

median_training_score_by_employment_type = drivers_df.groupby('employment_type')['training_score'].median()

print("Median training score by employment type:")
print(median_training_score_by_employment_type)

Median training score by employment type:
employment_type
Contract    75.45
FullTime    75.70
PartTime    74.10
Name: training_score, dtype: float64

In [3]:

drivers_df['training_score'] = drivers_df.groupby('employment_type')['training_score'].transform(lambda x: x.fillna(x.median()))


print("\nNull values in 'training_score' after imputation:")
print(drivers_df['training_score'].isnull().sum())

Null values in 'training_score' after imputation:
0

In [4]:

print("\nDataFrame after imputing missing training scores:")
display(drivers_df.head())

DataFrame after imputing missing training scores:

,driver_id,base_zone,employment_type,years_experience,training_score,driver_rating,shift_preference,active_flag
0,D001,AIRPORT,FullTime,8,67.8,3.54,Morning,1
1,D002,Central,FullTime,4,42.4,3.94,Evening,1
2,D003,AIRPORT,FullTime,11,96.5,5.00,Evening,1
3,D004,Airport,PartTime,13,88.9,4.75,Morning,1
4,D005,north,FullTime,3,69.7,4.14,Morning,1

In [7]:
import os

output_folder = 'corrected_data'
output_filename = 'corrected_drivers.csv'

if not os.path.exists(output_folder):
    os.makedirs(output_folder)


output_filepath = os.path.join(output_folder, output_filename)

drivers_df.to_csv(output_filepath, index=False)

print(f"DataFrame successfully saved to '{output_filepath}'")

DataFrame successfully saved to 'corrected_data/corrected_drivers.csv'

Complaints Table

In [8]:
import pandas as pd

complaints_df = pd.read_csv('/content/complaints.csv')
print("Null values in each column of the complaints table:")
print(complaints_df.isnull().sum())

Null values in each column of the complaints table:
complaint_id            0
customer_id             0
order_id                0
complaint_type          0
channel                 0
severity                0
created_at              0
status                  0
resolution_days         0
compensation_amount    16
dtype: int64

### Imputing Missing `compensation_amount` in `complaints_df`

We will categorize `resolution_days` and then use the median `compensation_amount` within each category to fill missing `compensation_amount` values.

In [9]:

bins = [1, 5, 10, 15, complaints_df['resolution_days'].max() + 1]
labels = ['1-5 days', '5-10 days', '10-15 days', '15+ days']


complaints_df['resolution_days_category'] = pd.cut(
    complaints_df['resolution_days'],
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
)


median_compensation_by_category = complaints_df.groupby('resolution_days_category')['compensation_amount'].median()

print("Median compensation amount by resolution days category:")
print(median_compensation_by_category)


complaints_df['compensation_amount'] = complaints_df.groupby('resolution_days_category')['compensation_amount'].transform(lambda x: x.fillna(x.median()))


print("\nNull values in 'compensation_amount' after imputation:")
print(complaints_df['compensation_amount'].isnull().sum())


print("\nDataFrame after imputing missing compensation amounts:")
display(complaints_df.head())

Median compensation amount by resolution days category:
resolution_days_category
1-5 days      13.815
5-10 days     18.285
10-15 days    22.730
15+ days      33.090
Name: compensation_amount, dtype: float64

Null values in 'compensation_amount' after imputation:
0

DataFrame after imputing missing compensation amounts:

/tmp/ipykernel_3863/231511712.py:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  median_compensation_by_category = complaints_df.groupby('resolution_days_category')['compensation_amount'].median()
/tmp/ipykernel_3863/231511712.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  complaints_df['compensation_amount'] = complaints_df.groupby('resolution_days_category')['compensation_amount'].transform(lambda x: x.fillna(x.median()))

,complaint_id,customer_id,order_id,complaint_type,channel,severity,created_at,status,resolution_days,compensation_amount,resolution_days_category
0,CP0001,C0464,O00814,AppIssue,App,High,2025-03-30 02:36:00,Open,11,23.99,10-15 days
1,CP0002,C0056,O00628,MissedPickup,Phone,Medium,2024-11-07 10:05:00,Open,4,21.64,1-5 days
2,CP0003,C0469,O00384,Delay,Chatbot,High,2024-01-02 15:47:00,Open,16,26.41,15+ days
3,CP0004,C0631,O00406,Delay,App,Medium,2025-01-14 13:07:00,AwaitingCustomer,7,23.44,5-10 days
4,CP0005,C0535,O00154,Delay,Email,Medium,2024-08-31 05:56:00,Resolved,1,16.18,1-5 days

In [10]:
import os

output_folder = 'corrected_data'
output_filename_complaints = 'corrected_complaints.csv'


if not os.path.exists(output_folder):
    os.makedirs(output_folder)


output_filepath_complaints = os.path.join(output_folder, output_filename_complaints)


complaints_df.to_csv(output_filepath_complaints, index=False)

print(f"DataFrame successfully saved to '{output_filepath_complaints}'")

DataFrame successfully saved to 'corrected_data/corrected_complaints.csv'

Customer Table

In [11]:
import pandas as pd

customers_df = pd.read_csv('/content/customers.csv')
print("Null values in each column of the customers table:")
print(customers_df.isnull().sum())

Null values in each column of the customers table:
customer_id              0
age                      0
home_zone                0
customer_type            0
signup_date              0
loyalty_score           20
app_engagement_score     0
preferred_channel       13
account_status           0
dtype: int64

### Imputing Missing `loyalty_score` in `customers_df`

We will fill the missing `loyalty_score` values by using the median `loyalty_score` for each `customer_type`.

In [14]:

median_loyalty_score_by_customer_type = customers_df.groupby('customer_type')['loyalty_score'].median()

print("Median loyalty score by customer type:")
print(median_loyalty_score_by_customer_type)

customers_df['loyalty_score'] = customers_df.groupby('customer_type')['loyalty_score'].transform(lambda x: x.fillna(x.median()))

print("\nNull values in 'loyalty_score' after imputation:")
print(customers_df['loyalty_score'].isnull().sum())

print("\nDataFrame after imputing missing loyalty scores:")
display(customers_df.head())

Median loyalty score by customer type:
customer_type
Consumer      60.0
Enterprise    61.5
SME           56.1
Name: loyalty_score, dtype: float64

Null values in 'loyalty_score' after imputation:
0

DataFrame after imputing missing loyalty scores:

,customer_id,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status
0,C0001,26,North,SME,2024-11-27 04:25:00,44.9,69.2,App,Active
1,C0002,61,AIRPORT,Consumer,2025-10-28 01:04:00,55.4,66.6,App,Active
2,C0003,66,East,Consumer,2025-07-02 03:23:00,75.9,33.8,NaN,Active
3,C0004,75,CENTRAL,Consumer,2025-08-19 01:58:00,32.5,33.0,App,Active
4,C0005,26,Riverside,Consumer,2025-06-03 06:02:00,55.9,100.0,Web,Active

### Imputing Missing `preferred_channel` in `customers_df`

We will impute the missing `preferred_channel` based on two sources:
1.  **Primary Source (`orders_df`)**: For customers who have placed orders, we will use their most frequently used `booking_channel`.
2.  **Secondary Source (`app_events_df`)**: For customers who have not placed orders (and still have a null `preferred_channel`), we will check their `device_type` in `app_events_df`. If their `device_type` is 'Android' or 'iOS', we will set their `preferred_channel` to 'App'.

In [18]:
import pandas as pd

orders_df = pd.read_csv('/content/orders.csv')


most_frequent_channel = orders_df.groupby('customer_id')['booking_channel'].agg(lambda x: x.mode()[0] if not x.mode().empty else None).reset_index()
most_frequent_channel.rename(columns={'booking_channel': 'inferred_preferred_channel'}, inplace=True)

customers_df = customers_df.merge(most_frequent_channel, on='customer_id', how='left')

customers_df['preferred_channel'] = customers_df['preferred_channel'].fillna(customers_df['inferred_preferred_channel'])

customers_df.drop(columns=['inferred_preferred_channel'], inplace=True)

print("Null values in 'preferred_channel' after primary imputation (from orders):")
print(customers_df['preferred_channel'].isnull().sum())

Null values in 'preferred_channel' after primary imputation (from orders):
2

In [37]:

customers_with_null_channel = customers_df[customers_df['preferred_channel'].isnull()]['customer_id'].unique()

app_events_for_null_customers = app_events_df[
    (app_events_df['customer_id'].isin(customers_with_null_channel)) &
    (app_events_df['device_type'].isin(['Android', 'iOS']))
].copy()

=inferred_app_channel = app_events_for_null_customers.groupby('customer_id')['device_type'].first().reset_index()
inferred_app_channel['inferred_app_channel'] = 'App'

customers_df = customers_df.merge(inferred_app_channel[['customer_id', 'inferred_app_channel']], on='customer_id', how='left')

customers_df['preferred_channel'] = customers_df['preferred_channel'].fillna(customers_df['inferred_app_channel'])

customers_df.drop(columns=['inferred_app_channel'], inplace=True)

print("\nNull values in 'preferred_channel' after secondary imputation (from app events):")
print(customers_df['preferred_channel'].isnull().sum())

print("\nDataFrame after imputing missing preferred channels:")
display(customers_df.head())

Null values in 'preferred_channel' after secondary imputation (from app events):
0

DataFrame after imputing missing preferred channels:

,customer_id,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status
0,C0001,26,North,SME,2024-11-27 04:25:00,44.9,69.2,App,Active
1,C0002,61,AIRPORT,Consumer,2025-10-28 01:04:00,55.4,66.6,App,Active
2,C0003,66,East,Consumer,2025-07-02 03:23:00,75.9,33.8,App,Active
3,C0004,75,CENTRAL,Consumer,2025-08-19 01:58:00,32.5,33.0,App,Active
4,C0005,26,Riverside,Consumer,2025-06-03 06:02:00,55.9,100.0,Web,Active

In [38]:
import os

output_folder = 'corrected_data'
output_filename_customers = 'corrected_customers.csv'

if not os.path.exists(output_folder):
    os.makedirs(output_folder)

output_filepath_customers = os.path.join(output_folder, output_filename_customers)

customers_df.to_csv(output_filepath_customers, index=False)

print(f"DataFrame successfully saved to '{output_filepath_customers}'")

DataFrame successfully saved to 'corrected_data/corrected_customers.csv'

Deliveries Table

In [39]:
import pandas as pd

deliveries_df = pd.read_csv('/content/deliveries.csv')

print("Null values in each column of the Deliveries table:")
print(deliveries_df.isnull().sum())

Null values in each column of the Deliveries table:
delivery_id                       0
order_id                          0
driver_id                         0
vehicle_id                        0
hub_id                            0
dispatch_time                     0
delivery_completed_at            19
delivery_status                   0
route_distance_km                 0
manual_route_override_count       0
proof_of_completion_missing       0
customer_rating_post_delivery    14
fuel_or_charge_cost               0
dtype: int64

In [40]:

deliveries_df['dispatch_time'] = pd.to_datetime(deliveries_df['dispatch_time'])
deliveries_df['delivery_completed_at'] = pd.to_datetime(deliveries_df['delivery_completed_at'])
app_events_df['event_timestamp'] = pd.to_datetime(app_events_df['event_timestamp'])

missing_delivery_completed_at_orders = deliveries_df[deliveries_df['delivery_completed_at'].isnull()]['order_id'].unique()


relevant_app_events = app_events_df[
    (app_events_df['order_id'].isin(missing_delivery_completed_at_orders)) &
    (app_events_df['event_type'].isin(['eta_refresh', 'track_order']))
].copy()


max_event_timestamp_for_delivery = relevant_app_events.groupby('order_id')['event_timestamp'].max().reset_index()
max_event_timestamp_for_delivery.rename(columns={'event_timestamp': 'inferred_delivery_completed_at'}, inplace=True)

deliveries_df = deliveries_df.merge(max_event_timestamp_for_delivery, on='order_id', how='left')

deliveries_df['delivery_completed_at'] = deliveries_df['delivery_completed_at'].fillna(deliveries_df['inferred_delivery_completed_at'])

deliveries_df.drop(columns=['inferred_delivery_completed_at'], inplace=True)

print("Null values in 'delivery_completed_at' after imputation from app_events:")
print(deliveries_df['delivery_completed_at'].isnull().sum())

print("\nDataFrame after imputing missing delivery completed times:")
display(deliveries_df.head())

Null values in 'delivery_completed_at' after imputation from app_events:
17

DataFrame after imputing missing delivery completed times:

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2024-06-19 09:05:59.904311,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,2025-06-02 21:45:32.366770,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,2024-03-09 23:30:08.103702,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,2025-09-21 15:45:34.131056,OnTime,14.52,1,0,4.18,9.22

In [43]:

successful_deliveries = deliveries_df[deliveries_df['delivery_status'].isin(['OnTime', 'Delayed'])].copy()


successful_deliveries['trip_duration'] = successful_deliveries['delivery_completed_at'] - successful_deliveries['dispatch_time']


average_trip_duration = successful_deliveries['trip_duration'].mean()

print(f"Average trip duration for successful deliveries: {average_trip_duration}")

missing_delivery_completed_at_indices = deliveries_df[deliveries_df['delivery_completed_at'].isnull()].index

deliveries_df.loc[missing_delivery_completed_at_indices, 'delivery_completed_at'] = \
    deliveries_df.loc[missing_delivery_completed_at_indices, 'dispatch_time'] + average_trip_duration

print("\nNull values in 'delivery_completed_at' after final imputation:")
print(deliveries_df['delivery_completed_at'].isnull().sum())

print("\nDataFrame after final imputation of missing delivery completed times:")
display(deliveries_df.head())

Average trip duration for successful deliveries: -1 days +08:15:00.703097580

Null values in 'delivery_completed_at' after final imputation:
0

DataFrame after final imputation of missing delivery completed times:

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2024-06-19 09:05:59.904311,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,2025-06-02 21:45:32.366770,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,2024-03-09 23:30:08.103702,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,2025-09-21 15:45:34.131056,OnTime,14.52,1,0,4.18,9.22

In [44]:
import os

output_folder = 'corrected_data'
output_filename_deliveries = 'corrected_deliveries.csv'


if not os.path.exists(output_folder):
    os.makedirs(output_folder)

output_filepath_deliveries = os.path.join(output_folder, output_filename_deliveries)

deliveries_df.to_csv(output_filepath_deliveries, index=False)

print(f"DataFrame successfully saved to '{output_filepath_deliveries}'")

DataFrame successfully saved to 'corrected_data/corrected_deliveries.csv'

In [45]:

global_median_rating = deliveries_df['customer_rating_post_delivery'].median()
print(f"Global median customer rating: {global_median_rating:.2f}")

driver_avg_ratings = deliveries_df.groupby('driver_id')['customer_rating_post_delivery'].transform(lambda x: x.mean() if x.notnull().any() else None)

deliveries_df['customer_rating_post_delivery'] = deliveries_df['customer_rating_post_delivery'].fillna(driver_avg_ratings)

deliveries_df['customer_rating_post_delivery'] = deliveries_df['customer_rating_post_delivery'].fillna(global_median_rating)

print("\nNull values in 'customer_rating_post_delivery' after imputation:")
print(deliveries_df['customer_rating_post_delivery'].isnull().sum())

print("\nDataFrame after imputing missing customer ratings:")
display(deliveries_df.head())

Global median customer rating: 4.04

Null values in 'customer_rating_post_delivery' after imputation:
0

DataFrame after imputing missing customer ratings:

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2024-06-19 09:05:59.904311,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,2025-06-02 21:45:32.366770,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,2024-03-09 23:30:08.103702,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,2025-09-21 15:45:34.131056,OnTime,14.52,1,0,4.18,9.22

In [46]:
import os

output_folder = 'corrected_data'
output_filename_deliveries = 'corrected_deliveries.csv'


if not os.path.exists(output_folder):
    os.makedirs(output_folder)


output_filepath_deliveries = os.path.join(output_folder, output_filename_deliveries)
deliveries_df.to_csv(output_filepath_deliveries, index=False)

print(f"Corrected Deliveries DataFrame successfully saved to '{output_filepath_deliveries}'")

Corrected Deliveries DataFrame successfully saved to 'corrected_data/corrected_deliveries.csv'

Incidents Table

In [48]:
import pandas as pd

incidents_df = pd.read_csv('/content/incidents.csv')

print("Null values in each column of the Incidents table:")
print(incidents_df.isnull().sum())

Null values in each column of the Incidents table:
incident_id           0
delivery_id           0
incident_type         0
reported_at           0
severity              0
resolution_status     0
resolved_hours       17
dtype: int64

In [49]:

global_median_resolved_hours = incidents_df['resolved_hours'].median()
print(f"Global median resolved hours: {global_median_resolved_hours:.2f}")

incidents_df['resolved_hours'] = incidents_df.groupby(['incident_type', 'severity'])['resolved_hours'].transform(lambda x: x.fillna(x.median()))

incidents_df['resolved_hours'] = incidents_df.groupby('incident_type')['resolved_hours'].transform(lambda x: x.fillna(x.median()))

incidents_df['resolved_hours'] = incidents_df['resolved_hours'].fillna(global_median_resolved_hours)

print("\nNull values in 'resolved_hours' after imputation:")
print(incidents_df['resolved_hours'].isnull().sum())

print("\nDataFrame after imputing missing resolved hours:")
display(incidents_df.head())

Global median resolved hours: 11.50

Null values in 'resolved_hours' after imputation:
0

DataFrame after imputing missing resolved hours:

,incident_id,delivery_id,incident_type,reported_at,severity,resolution_status,resolved_hours
0,I0001,DL00221,BatteryAlert,2024-03-11 23:46:00,Medium,Escalated,12.3
1,I0002,DL00578,BatteryAlert,2024-02-21 10:56:00,Low,Open,9.6
2,I0003,DL00175,TemperatureIssue,2025-04-17 23:22:00,Medium,Open,22.0
3,I0004,DL00417,ProofMissing,2025-02-09 00:16:00,Medium,Closed,9.8
4,I0005,DL00897,RouteDeviation,2025-01-04 02:49:00,Low,Open,13.0

In [50]:
import os

output_folder = 'corrected_data'
output_filename_incidents = 'corrected_incidents.csv'


if not os.path.exists(output_folder):
    os.makedirs(output_folder)


output_filepath_incidents = os.path.join(output_folder, output_filename_incidents)


incidents_df.to_csv(output_filepath_incidents, index=False)

print(f"DataFrame successfully saved to '{output_filepath_incidents}'")

DataFrame successfully saved to 'corrected_data/corrected_incidents.csv'

Orders Table

In [51]:
import pandas as pd

orders_df = pd.read_csv('/content/orders.csv')

print("Null values in each column of the Orders table:")
print(orders_df.isnull().sum())

Null values in each column of the Orders table:
order_id                  0
customer_id               0
service_type              0
order_created_at          0
promised_window_hours     0
pickup_zone               0
dropoff_zone              0
priority_level            0
order_value               0
booking_channel          25
special_handling_flag     0
dtype: int64

### Imputing Missing `booking_channel` in `orders_df`

We will impute missing `booking_channel` values by:
1.  Identifying orders with a null `booking_channel`.
2.  Searching the `app_events_df` for records associated with these `order_id`s.
3.  Inferring the `booking_channel` based on the `device_type` in `app_events_df` (`Android`/`iOS` -> 'App', `Web` -> 'Web').

In [52]:
orders_df['order_created_at'] = pd.to_datetime(orders_df['order_created_at'])
app_events_df['event_timestamp'] = pd.to_datetime(app_events_df['event_timestamp'])

orders_with_null_channel = orders_df[orders_df['booking_channel'].isnull()].copy()

null_order_ids = orders_with_null_channel['order_id'].unique()

# Filter app_events_df for these order_ids
relevant_app_events = app_events_df[app_events_df['order_id'].isin(null_order_ids)].copy()

# Create a mapping from order_id to inferred booking_channel based on device_type
def get_inferred_channel(device_types):
    if 'Android' in device_types or 'iOS' in device_types:
        return 'App'
    if 'Web' in device_types:
        return 'Web'
    return None

inferred_channels = relevant_app_events.groupby('order_id')['device_type'].apply(get_inferred_channel).reset_index(name='inferred_channel')

orders_df = orders_df.merge(inferred_channels, on='order_id', how='left')

orders_df['booking_channel'] = orders_df['booking_channel'].fillna(orders_df['inferred_channel'])

orders_df.drop(columns=['inferred_channel'], inplace=True)

print("\nNull values in 'booking_channel' after imputation:")
print(orders_df['booking_channel'].isnull().sum())

print("\nDataFrame after imputing missing booking channels:")
display(orders_df.head())

Null values in 'booking_channel' after imputation:
25

DataFrame after imputing missing booking channels:

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,AIRPORT,Low,109.30,App,0
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,AIRPORT,High,33.50,Phone,0
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,RiverSide,North,Medium,10.04,App,1
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,SOUTH,Low,125.58,Phone,0

In [54]:

orders_still_null_channel = orders_df[orders_df['booking_channel'].isnull()].copy()

merged_with_customers = orders_still_null_channel.merge(
    customers_df[['customer_id', 'preferred_channel']],
    on='customer_id',
    how='left',
    suffixes=('_order', '_customer')
)

orders_df.loc[orders_df['booking_channel'].isnull(), 'booking_channel'] = (
    orders_df.loc[orders_df['booking_channel'].isnull()].merge(
        customers_df[['customer_id', 'preferred_channel']],
        on='customer_id',
        how='left'
    )['preferred_channel']
)

print("\nNull values in 'booking_channel' after secondary imputation (from customers_df):")
print(orders_df['booking_channel'].isnull().sum())

Null values in 'booking_channel' after secondary imputation (from customers_df):
25

In [55]:

global_most_frequent_channel = orders_df['booking_channel'].mode()[0]
print(f"Global most frequent booking channel: {global_most_frequent_channel}")

orders_df['booking_channel'] = orders_df['booking_channel'].fillna(global_most_frequent_channel)

print("\nNull values in 'booking_channel' after final imputation (global mode):")
print(orders_df['booking_channel'].isnull().sum())

print("\nDataFrame after all booking channel imputations:")
display(orders_df.head())

Global most frequent booking channel: App

Null values in 'booking_channel' after final imputation (global mode):
0

DataFrame after all booking channel imputations:

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,AIRPORT,Low,109.30,App,0
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,AIRPORT,High,33.50,Phone,0
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,RiverSide,North,Medium,10.04,App,1
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,SOUTH,Low,125.58,Phone,0

In [56]:
import os

output_folder = 'corrected_data'
output_filename_orders = 'corrected_orders.csv'

if not os.path.exists(output_folder):
    os.makedirs(output_folder)

output_filepath_orders = os.path.join(output_folder, output_filename_orders)

orders_df.to_csv(output_filepath_orders, index=False)

print(f"DataFrame successfully saved to '{output_filepath_orders}'")

DataFrame successfully saved to 'corrected_data/corrected_orders.csv'

Vehicles Table

In [57]:
import pandas as pd

vehicles_df = pd.read_csv('/content/vehicles.csv')

print("Null values in each column of the Vehicles table:")
print(vehicles_df.isnull().sum())

Null values in each column of the Vehicles table:
vehicle_id            0
vehicle_type          0
assigned_zone         0
commission_date       0
battery_health_pct    4
odometer_km           0
maintenance_status    0
telematics_version    0
dtype: int64

In [58]:
global_median_battery_health = vehicles_df['battery_health_pct'].median()
print(f"Global median battery health percentage: {global_median_battery_health:.2f}")

bin_width = 50000
vehicles_df['mileage_bin'] = (vehicles_df['odometer_km'] // bin_width * bin_width).astype(str) + '-' + \
                             ((vehicles_df['odometer_km'] // bin_width + 1) * bin_width).astype(str)

vehicles_df['battery_health_pct'] = vehicles_df.groupby(['vehicle_type', 'mileage_bin'])['battery_health_pct'].transform(lambda x: x.fillna(x.median()))

print("\nNull values in 'battery_health_pct' after primary imputation (type + bin):")
print(vehicles_df['battery_health_pct'].isnull().sum())

Global median battery health percentage: 78.05

Null values in 'battery_health_pct' after primary imputation (type + bin):
0

In [59]:
vehicles_df['battery_health_pct'] = vehicles_df.groupby('vehicle_type')['battery_health_pct'].transform(lambda x: x.fillna(x.median()))

print("\nNull values in 'battery_health_pct' after secondary imputation (type only):")
print(vehicles_df['battery_health_pct'].isnull().sum())

Null values in 'battery_health_pct' after secondary imputation (type only):
0

In [60]:
vehicles_df['battery_health_pct'] = vehicles_df['battery_health_pct'].fillna(global_median_battery_health)

print("\nNull values in 'battery_health_pct' after final imputation:")
print(vehicles_df['battery_health_pct'].isnull().sum())

vehicles_df.drop(columns=['mileage_bin'], inplace=True)

print("\nDataFrame after imputing missing battery health percentages:")
display(vehicles_df.head())

Null values in 'battery_health_pct' after final imputation:
0

DataFrame after imputing missing battery health percentages:

,vehicle_id,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version
0,V001,EV,North,2024-12-28 23:48:00,71.8,56928,Active,v2.2
1,V002,EV,AIRPORT,2024-04-21 16:14:00,67.9,159368,InRepair,v2.2
2,V003,CargoVan,north,2025-11-24 23:59:00,91.7,219359,Active,v2.1
3,V004,Hybrid,RiverSide,2024-06-07 13:21:00,80.5,36310,Active,v2.2
4,V005,CargoVan,West,2025-11-15 11:08:00,58.6,146638,Active,v2.2

In [61]:
import os

output_folder = 'corrected_data'
output_filename_vehicles = 'corrected_vehicles.csv'

if not os.path.exists(output_folder):
    os.makedirs(output_folder)

output_filepath_vehicles = os.path.join(output_folder, output_filename_vehicles)

vehicles_df.to_csv(output_filepath_vehicles, index=False)

print(f"DataFrame successfully saved to '{output_filepath_vehicles}'")

DataFrame successfully saved to 'corrected_data/corrected_vehicles.csv'

App Events Table

In [19]:
import pandas as pd

app_events_df = pd.read_csv('/content/app_events.csv')

In [24]:
import pandas as pd

deliveries_df = pd.read_csv('/content/deliveries.csv')

In [81]:
print("Null values in each column of the App Events table:")
print(app_events_df.isnull().sum())

Null values in each column of the App Events table:
event_id             0
customer_id          0
order_id           143
event_timestamp      0
event_type           0
session_id           0
device_type          0
zone_context         0
api_latency_ms       0
success_flag         0
dtype: int64

In [25]:
import pandas as pd


if 'app_events_df' not in locals() and 'app_events_df' not in globals():
    app_events_df = pd.read_csv('/content/app_events.csv')

app_events_df['order_id'] = app_events_df.groupby('session_id')['order_id'].ffill().bfill()

print("Null values in 'order_id' after session-based propagation:")
print(app_events_df['order_id'].isnull().sum())

print("\nDataFrame after session-based imputation:")
display(app_events_df.head())

Null values in 'order_id' after session-based propagation:
0

DataFrame after session-based imputation:

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag
0,AE00180,C0003,O00599,2024-04-05 22:39:00,cancel_attempt,S48720,Android,AIRPORT,282,1
1,AE00609,C0003,O00895,2025-06-27 12:45:00,payment_retry,S43719,iOS,Riverside,715,1
2,AE00156,C0004,O00998,2025-05-12 19:56:00,chat_opened,S19094,Android,NORTH,618,1
3,AE00142,C0005,O00103,2024-04-18 04:39:00,track_order,S33250,Android,WEST,187,1
4,AE00412,C0005,O00716,2025-12-17 03:49:00,search_route,S77981,Android,West,363,1

In [21]:
import os
import pandas as pd


if 'app_events_df' not in locals() and 'app_events_df' not in globals():
    app_events_df = pd.read_csv('/content/app_events.csv')

output_folder = 'corrected_data'
output_filename_app_events = 'corrected_app_events.csv'


if not os.path.exists(output_folder):
    os.makedirs(output_folder)


output_filepath_app_events = os.path.join(output_folder, output_filename_app_events)

app_events_df.to_csv(output_filepath_app_events, index=False)

print(f"DataFrame successfully saved to '{output_filepath_app_events}'")

DataFrame successfully saved to 'corrected_data/corrected_app_events.csv'

In [26]:
import pandas as pd


if 'orders_df' not in locals() and 'orders_df' not in globals():
    orders_df = pd.read_csv('/content/orders.csv')

if 'app_events_df' not in locals() and 'app_events_df' not in globals():
    app_events_df = pd.read_csv('/content/app_events.csv')

app_events_df['event_timestamp'] = pd.to_datetime(app_events_df['event_timestamp'])
orders_df['order_created_at'] = pd.to_datetime(orders_df['order_created_at'])


app_events_df = app_events_df.sort_values(by=['customer_id', 'event_timestamp']).reset_index(drop=True)
orders_df = orders_df.sort_values(by=['customer_id', 'order_created_at']).reset_index(drop=True)

app_events_to_merge = app_events_df[app_events_df['order_id'].isnull()].copy()

if not app_events_to_merge.empty:

    app_events_to_merge = app_events_to_merge.sort_values(by=['customer_id', 'event_timestamp']).reset_index(drop=True)


    merged_asof_result = pd.merge_asof(
        app_events_to_merge, # Use the freshly sorted subset
        orders_df[['customer_id', 'order_id', 'order_created_at']],
        left_on='event_timestamp',
        right_on='order_created_at',
        by='customer_id',
        direction='nearest', # Match nearest timestamp (before or after)
        tolerance=pd.Timedelta('1 hour'), # Within 1 hour
        suffixes=('_event', '_order_inferred')
    )


    inferred_ids = merged_asof_result[['event_id', 'order_id_order_inferred']].copy()
    inferred_ids.rename(columns={'order_id_order_inferred': 'inferred_order_id'}, inplace=True)


    app_events_df = app_events_df.merge(inferred_ids, on='event_id', how='left')


    app_events_df['order_id'] = app_events_df['order_id'].fillna(app_events_df['inferred_order_id'])


    app_events_df.drop(columns=['inferred_order_id'], inplace=True)
else:
    print("No null 'order_id' values remaining in app_events_df for time-based mapping with orders_df.")

print("Null values in 'order_id' after time-based mapping with orders_df:")
print(app_events_df['order_id'].isnull().sum())

print("\nDataFrame after time-based imputation:")
display(app_events_df.head())

No null 'order_id' values remaining in app_events_df for time-based mapping with orders_df.
Null values in 'order_id' after time-based mapping with orders_df:
0

DataFrame after time-based imputation:

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag
0,AE00180,C0003,O00599,2024-04-05 22:39:00,cancel_attempt,S48720,Android,AIRPORT,282,1
1,AE00609,C0003,O00895,2025-06-27 12:45:00,payment_retry,S43719,iOS,Riverside,715,1
2,AE00156,C0004,O00998,2025-05-12 19:56:00,chat_opened,S19094,Android,NORTH,618,1
3,AE00142,C0005,O00103,2024-04-18 04:39:00,track_order,S33250,Android,WEST,187,1
4,AE00412,C0005,O00716,2025-12-17 03:49:00,search_route,S77981,Android,West,363,1

In [27]:
import pandas as pd

# Ensure deliveries_df is loaded before operations are performed on it
if 'deliveries_df' not in locals() and 'deliveries_df' not in globals():
    deliveries_df = pd.read_csv('/content/deliveries.csv')
# Ensure app_events_df is loaded as well, in case of partial execution
if 'app_events_df' not in locals() and 'app_events_df' not in globals():
    app_events_df = pd.read_csv('/content/app_events.csv')

# Ensure deliveries_df timestamp columns are in datetime format
deliveries_df['dispatch_time'] = pd.to_datetime(deliveries_df['dispatch_time'])
deliveries_df['delivery_completed_at'] = pd.to_datetime(deliveries_df['delivery_completed_at'])

# Filter app_events_df for remaining null order_ids and relevant event types
app_events_to_match = app_events_df[
    (app_events_df['order_id'].isnull()) &
    (app_events_df['event_type'].isin(['track_order', 'eta_refresh']))
].copy()

if not app_events_to_match.empty:
    # Prepare deliveries_df with relevant columns and ensure non-null timestamps
    delivery_tracking_info = deliveries_df[
        ['customer_id', 'order_id', 'dispatch_time', 'delivery_completed_at']
    ].dropna(subset=['dispatch_time', 'delivery_completed_at']).copy()

    # Merge app_events_to_match with delivery_tracking_info on customer_id
    merged_delivery_match = pd.merge(
        app_events_to_match,
        delivery_tracking_info,
        on='customer_id',
        how='left',
        suffixes=('_event', '_delivery')
    )

    # Filter for matches where event_timestamp is within dispatch_time and delivery_completed_at
    # And where the delivery order_id is not null (as it's the target)
    valid_matches = merged_delivery_match[
        (merged_delivery_match['event_timestamp'] >= merged_delivery_match['dispatch_time']) &
        (merged_delivery_match['event_timestamp'] <= merged_delivery_match['delivery_completed_at']) &
        (merged_delivery_match['order_id_delivery'].notnull())
    ].copy()

    if not valid_matches.empty:
        # From these valid matches, select the first inferred order_id for each event_id
        # This handles cases where an event might fall into multiple delivery windows
        # (e.g., if a customer has overlapping deliveries, pick the first one chronologically)
        inferred_delivery_order_ids = valid_matches.groupby('event_id').first()['order_id_delivery'].reset_index()
        inferred_delivery_order_ids.rename(columns={'order_id_delivery': 'inferred_order_id_from_delivery'}, inplace=True)

        # Merge these inferred order_ids back to the original app_events_df
        app_events_df = app_events_df.merge(inferred_delivery_order_ids, on='event_id', how='left')

        # Fill any remaining null 'order_id' values in app_events_df with the inferred ones from deliveries
        app_events_df['order_id'] = app_events_df['order_id'].fillna(app_events_df['inferred_order_id_from_delivery'])

        # Drop the temporary inferred column
        app_events_df.drop(columns=['inferred_order_id_from_delivery'], inplace=True)
    else:
        print("No valid matches found in deliveries_df for remaining null 'order_id' values.")
else:
    print("No null 'order_id' values remaining in app_events_df for tracking window imputation with deliveries_df.")


# Check remaining null values in 'order_id'
print("Null values in 'order_id' after tracking window imputation with deliveries_df:")
print(app_events_df['order_id'].isnull().sum())

# Display the first few rows to show the updated DataFrame
print("\nDataFrame after delivery tracking window imputation:")
display(app_events_df.head())

No null 'order_id' values remaining in app_events_df for tracking window imputation with deliveries_df.
Null values in 'order_id' after tracking window imputation with deliveries_df:
0

DataFrame after delivery tracking window imputation:

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag
0,AE00180,C0003,O00599,2024-04-05 22:39:00,cancel_attempt,S48720,Android,AIRPORT,282,1
1,AE00609,C0003,O00895,2025-06-27 12:45:00,payment_retry,S43719,iOS,Riverside,715,1
2,AE00156,C0004,O00998,2025-05-12 19:56:00,chat_opened,S19094,Android,NORTH,618,1
3,AE00142,C0005,O00103,2024-04-18 04:39:00,track_order,S33250,Android,WEST,187,1
4,AE00412,C0005,O00716,2025-12-17 03:49:00,search_route,S77981,Android,West,363,1